### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by csokun** [JakeUrban/polaris-project-template#1]
Hi Jake,

Thanks for sharing the polaris-project-template, as django newbie I was hope that this template can get me up to speed.
Unfortunately, I was wrong `docker-compose build` is the first thing I tried and it wasn't successful. Would be much appreciate if you could provide some additional guidance to get the application up & running.

Kind regards,
Sokun

```bash
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anchor/manage.py", line 21, in <module>
    main()
  File "anchor/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/anchor/anchor/settings.py", line 27, in <module>
    f"unable to find .env file in {BASE_DIR}"
django.core.exceptions.ImproperlyConfigured: unable to find .env file in /code/anchor
The command '/bin/sh -c pip install pipenv && pipenv install && pipenv run python anchor/manage.py collectstatic --no-input' returned a non-zero code: 1
ERROR: Service 'server' failed to build : Build failed
```

**Comment by JakeUrban** [comment]
Hi @csokun, it looks like you don't have a `.env` file in your `/anchor` directory. This file is copied from your local directory into the docker container's file system.

**Comment by csokun** [comment]
Thanks @JakeUrban I managed to get everything built and deploy. Unfortunately, I'm stuck once again trying to integrate `SEP-24`. I know I missing something because `SRT` asset is working but my test asset keep failing.

![image](https://user-images.githubusercontent.com/29750/172558358-ec71142a-0342-44fa-b0dd-89106fa15ef6.png)

May be I haven't implement deposit & withdrawal login as mentioned in the docs https://django-polaris.readthedocs.io/en/stable/sep-24.html#integrations. I tried to use example AnchorDeposit code but this line `from .users import user_for_account, create_user` preventing the from running the code.

If there any working example code out there that you could pointing me to? or is there a way to mock implementation so that I can see how thing work end-to-end.

**Comment by csokun** [comment]
My bad there is a typo in my `NETWORK_PASSPHRASE` https://anchor-tests.stellar.org/ help me spot the problem.
